---
dist: bionic
language: python

python:
  - '3.8'

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential libpoppler-cpp-dev pkg-config python-dev

install:
  - pip install pipenv
  - pipenv sync --dev

script:
  - pipenv run mypy accountman
  - pipenv run python -m unittest discover tests
