---
dist: focal

language: python

python:
  - '3.8'

addons:
  apt:
    update: true
    packages:
      - build-essential
      - libpoppler-cpp-dev
      - pkg-config
      - python3-dev

install:
  - pip install pipenv
  - pipenv sync --dev

script:
  - pipenv run mypy accountman
  - pipenv run python -m unittest discover tests
