---
dist: focal

language: python

python:
  - '3.8'
  - '3.9'

addons:
  apt:
    update: true
    packages:
      - build-essential
      - libpoppler-cpp-dev
      - pkg-config
      - python3-dev

install:
  - pip install pipenv
  - pipenv sync --dev

script:
  - mypy accountman
  - python -m unittest discover
